name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: --cfg extra
    steps:
    - uses: actions/checkout@v4
    - run: |
        cargo test
        cargo bench
